services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - HEADLESS=true
    restart: unless-stopped


  scraper:
    build: ./
    container_name: scraper
    depends_on:
      - flaresolverr
    ports:
      - "8080:8080"
    volumes:
      - /data/mangascraper:/root/downloads
    environment:
      - PORT=8080
  