// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chapter struct {
	ChapterID    int32              `db:"chapter_id" json:"chapter_id"`
	MangaID      int32              `db:"manga_id" json:"manga_id"`
	ChapterSlug  string             `db:"chapter_slug" json:"chapter_slug"`
	Downloaded   pgtype.Bool        `db:"downloaded" json:"downloaded"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Status       pgtype.Text        `db:"status" json:"status"`
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ChapterNum   pgtype.Float4      `db:"chapter_num" json:"chapter_num"`
}

type Manga struct {
	MangaID   int32              `db:"manga_id" json:"manga_id"`
	Title     string             `db:"title" json:"title"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Page struct {
	PageID       int32              `db:"page_id" json:"page_id"`
	ChapterID    int32              `db:"chapter_id" json:"chapter_id"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	FileName     pgtype.Text        `db:"file_name" json:"file_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Downloaded   pgtype.Bool        `db:"downloaded" json:"downloaded"`
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	DownloadedAt pgtype.Timestamptz `db:"downloaded_at" json:"downloaded_at"`
	FilePath     pgtype.Text        `db:"file_path" json:"file_path"`
}
