// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chapter struct {
	ChapterID    int32              `db:"chapter_id"`
	MangaID      int32              `db:"manga_id"`
	ChapterSlug  string             `db:"chapter_slug"`
	Downloaded   pgtype.Bool        `db:"downloaded"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	Status       pgtype.Text        `db:"status"`
	ErrorMessage pgtype.Text        `db:"error_message"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
	ChapterNum   pgtype.Float4      `db:"chapter_num"`
}

type Manga struct {
	MangaID   int32              `db:"manga_id"`
	Title     string             `db:"title"`
	Slug      string             `db:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type Page struct {
	PageID       int32              `db:"page_id"`
	ChapterID    int32              `db:"chapter_id"`
	ImageUrl     string             `db:"image_url"`
	FileName     pgtype.Text        `db:"file_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	Downloaded   pgtype.Bool        `db:"downloaded"`
	ErrorMessage pgtype.Text        `db:"error_message"`
	DownloadedAt pgtype.Timestamptz `db:"downloaded_at"`
	FilePath     pgtype.Text        `db:"file_path"`
}
