// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteManga = `-- name: DeleteManga :exec
DELETE FROM manga WHERE manga_id = $1
`

func (q *Queries) DeleteManga(ctx context.Context, mangaID int32) error {
	_, err := q.db.Exec(ctx, deleteManga, mangaID)
	return err
}

const getAllManga = `-- name: GetAllManga :many
SELECT manga_id, title, slug, created_at
FROM manga ORDER BY created_at DESC
`

func (q *Queries) GetAllManga(ctx context.Context) ([]Manga, error) {
	rows, err := q.db.Query(ctx, getAllManga)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Manga
	for rows.Next() {
		var i Manga
		if err := rows.Scan(
			&i.MangaID,
			&i.Title,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT chapter_id, manga_id, chapter_slug, chapter_num, status,
       COALESCE(error_message, ''), created_at, updated_at
FROM chapter
WHERE chapter_id = $1
`

type GetChapterByIDRow struct {
	ChapterID    int32              `db:"chapter_id"`
	MangaID      int32              `db:"manga_id"`
	ChapterSlug  string             `db:"chapter_slug"`
	ChapterNum   pgtype.Float4      `db:"chapter_num"`
	Status       pgtype.Text        `db:"status"`
	ErrorMessage string             `db:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) GetChapterByID(ctx context.Context, chapterID int32) (GetChapterByIDRow, error) {
	row := q.db.QueryRow(ctx, getChapterByID, chapterID)
	var i GetChapterByIDRow
	err := row.Scan(
		&i.ChapterID,
		&i.MangaID,
		&i.ChapterSlug,
		&i.ChapterNum,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChapterBySlug = `-- name: GetChapterBySlug :one
SELECT chapter_id, manga_id, chapter_slug, chapter_num, status,
       COALESCE(error_message, ''), created_at, updated_at
FROM chapter
WHERE manga_id = $1 AND chapter_slug = $2
`

type GetChapterBySlugParams struct {
	MangaID     int32  `db:"manga_id"`
	ChapterSlug string `db:"chapter_slug"`
}

type GetChapterBySlugRow struct {
	ChapterID    int32              `db:"chapter_id"`
	MangaID      int32              `db:"manga_id"`
	ChapterSlug  string             `db:"chapter_slug"`
	ChapterNum   pgtype.Float4      `db:"chapter_num"`
	Status       pgtype.Text        `db:"status"`
	ErrorMessage string             `db:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) GetChapterBySlug(ctx context.Context, arg GetChapterBySlugParams) (GetChapterBySlugRow, error) {
	row := q.db.QueryRow(ctx, getChapterBySlug, arg.MangaID, arg.ChapterSlug)
	var i GetChapterBySlugRow
	err := row.Scan(
		&i.ChapterID,
		&i.MangaID,
		&i.ChapterSlug,
		&i.ChapterNum,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChaptersByManga = `-- name: GetChaptersByManga :many
SELECT chapter_id, manga_id, chapter_slug, chapter_num, status, COALESCE(error_message, ''), created_at, updated_at
FROM chapter
WHERE manga_id = $1
ORDER BY chapter_num ASC
`

type GetChaptersByMangaRow struct {
	ChapterID    int32              `db:"chapter_id"`
	MangaID      int32              `db:"manga_id"`
	ChapterSlug  string             `db:"chapter_slug"`
	ChapterNum   pgtype.Float4      `db:"chapter_num"`
	Status       pgtype.Text        `db:"status"`
	ErrorMessage string             `db:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) GetChaptersByManga(ctx context.Context, mangaID int32) ([]GetChaptersByMangaRow, error) {
	rows, err := q.db.Query(ctx, getChaptersByManga, mangaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByMangaRow
	for rows.Next() {
		var i GetChaptersByMangaRow
		if err := rows.Scan(
			&i.ChapterID,
			&i.MangaID,
			&i.ChapterSlug,
			&i.ChapterNum,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMangaByID = `-- name: GetMangaByID :one
SELECT manga_id, title, slug, created_at
FROM manga WHERE manga_id = $1
`

func (q *Queries) GetMangaByID(ctx context.Context, mangaID int32) (Manga, error) {
	row := q.db.QueryRow(ctx, getMangaByID, mangaID)
	var i Manga
	err := row.Scan(
		&i.MangaID,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMangaBySlug = `-- name: GetMangaBySlug :one
SELECT manga_id, title, slug, created_at
FROM manga WHERE slug = $1
`

func (q *Queries) GetMangaBySlug(ctx context.Context, slug string) (Manga, error) {
	row := q.db.QueryRow(ctx, getMangaBySlug, slug)
	var i Manga
	err := row.Scan(
		&i.MangaID,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getPagesByChapter = `-- name: GetPagesByChapter :many
SELECT page_id, chapter_id, image_url, file_name, file_path, COALESCE(error_message, ''), created_at, downloaded_at
FROM page WHERE chapter_id = $1
ORDER BY page_id
`

type GetPagesByChapterRow struct {
	PageID       int32              `db:"page_id"`
	ChapterID    int32              `db:"chapter_id"`
	ImageUrl     string             `db:"image_url"`
	FileName     pgtype.Text        `db:"file_name"`
	FilePath     pgtype.Text        `db:"file_path"`
	ErrorMessage string             `db:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	DownloadedAt pgtype.Timestamptz `db:"downloaded_at"`
}

func (q *Queries) GetPagesByChapter(ctx context.Context, chapterID int32) ([]GetPagesByChapterRow, error) {
	rows, err := q.db.Query(ctx, getPagesByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPagesByChapterRow
	for rows.Next() {
		var i GetPagesByChapterRow
		if err := rows.Scan(
			&i.PageID,
			&i.ChapterID,
			&i.ImageUrl,
			&i.FileName,
			&i.FilePath,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingChapters = `-- name: GetPendingChapters :many
SELECT chapter_id, manga_id, chapter_slug, chapter_num, status, created_at
FROM chapter
WHERE status != $1 AND status != $2
ORDER BY manga_id, chapter_num ASC
`

type GetPendingChaptersParams struct {
	Status   pgtype.Text `db:"status"`
	Status_2 pgtype.Text `db:"status_2"`
}

type GetPendingChaptersRow struct {
	ChapterID   int32              `db:"chapter_id"`
	MangaID     int32              `db:"manga_id"`
	ChapterSlug string             `db:"chapter_slug"`
	ChapterNum  pgtype.Float4      `db:"chapter_num"`
	Status      pgtype.Text        `db:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) GetPendingChapters(ctx context.Context, arg GetPendingChaptersParams) ([]GetPendingChaptersRow, error) {
	rows, err := q.db.Query(ctx, getPendingChapters, arg.Status, arg.Status_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingChaptersRow
	for rows.Next() {
		var i GetPendingChaptersRow
		if err := rows.Scan(
			&i.ChapterID,
			&i.MangaID,
			&i.ChapterSlug,
			&i.ChapterNum,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPages = `-- name: GetPendingPages :many
SELECT page_id, chapter_id, image_url, file_name, created_at
FROM page
WHERE downloaded = FALSE AND (error_message IS NULL OR error_message = '')
ORDER BY page_id
`

type GetPendingPagesRow struct {
	PageID    int32              `db:"page_id"`
	ChapterID int32              `db:"chapter_id"`
	ImageUrl  string             `db:"image_url"`
	FileName  pgtype.Text        `db:"file_name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) GetPendingPages(ctx context.Context) ([]GetPendingPagesRow, error) {
	rows, err := q.db.Query(ctx, getPendingPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingPagesRow
	for rows.Next() {
		var i GetPendingPagesRow
		if err := rows.Scan(
			&i.PageID,
			&i.ChapterID,
			&i.ImageUrl,
			&i.FileName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveChapter = `-- name: SaveChapter :one
INSERT INTO chapter (manga_id, chapter_slug, chapter_num, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (manga_id, chapter_slug) DO UPDATE SET chapter_num = EXCLUDED.chapter_num
RETURNING chapter_id
`

type SaveChapterParams struct {
	MangaID     int32         `db:"manga_id"`
	ChapterSlug string        `db:"chapter_slug"`
	ChapterNum  pgtype.Float4 `db:"chapter_num"`
	Status      pgtype.Text   `db:"status"`
}

func (q *Queries) SaveChapter(ctx context.Context, arg SaveChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveChapter,
		arg.MangaID,
		arg.ChapterSlug,
		arg.ChapterNum,
		arg.Status,
	)
	var chapter_id int32
	err := row.Scan(&chapter_id)
	return chapter_id, err
}

const saveManga = `-- name: SaveManga :one
INSERT INTO manga (title, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title
RETURNING manga_id
`

type SaveMangaParams struct {
	Title string `db:"title"`
	Slug  string `db:"slug"`
}

func (q *Queries) SaveManga(ctx context.Context, arg SaveMangaParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveManga, arg.Title, arg.Slug)
	var manga_id int32
	err := row.Scan(&manga_id)
	return manga_id, err
}

const savePage = `-- name: SavePage :one
INSERT INTO page (chapter_id, image_url, file_name, file_path, downloaded, error_message)
VALUES ($1, $2, $3, $4, FALSE, NULL)
ON CONFLICT DO NOTHING
RETURNING page_id
`

type SavePageParams struct {
	ChapterID int32       `db:"chapter_id"`
	ImageUrl  string      `db:"image_url"`
	FileName  pgtype.Text `db:"file_name"`
	FilePath  pgtype.Text `db:"file_path"`
}

func (q *Queries) SavePage(ctx context.Context, arg SavePageParams) (int32, error) {
	row := q.db.QueryRow(ctx, savePage,
		arg.ChapterID,
		arg.ImageUrl,
		arg.FileName,
		arg.FilePath,
	)
	var page_id int32
	err := row.Scan(&page_id)
	return page_id, err
}

const updateChapterStatus = `-- name: UpdateChapterStatus :exec
UPDATE chapter
SET status = $1,
    error_message = $2,
    updated_at = NOW()
WHERE chapter_id = $3
`

type UpdateChapterStatusParams struct {
	Status       pgtype.Text `db:"status"`
	ErrorMessage pgtype.Text `db:"error_message"`
	ChapterID    int32       `db:"chapter_id"`
}

func (q *Queries) UpdateChapterStatus(ctx context.Context, arg UpdateChapterStatusParams) error {
	_, err := q.db.Exec(ctx, updateChapterStatus, arg.Status, arg.ErrorMessage, arg.ChapterID)
	return err
}

const updatePageStatus = `-- name: UpdatePageStatus :exec
UPDATE page
SET downloaded = $1,
    error_message = $2,
    downloaded_at = $3
WHERE page_id = $4
`

type UpdatePageStatusParams struct {
	Downloaded   pgtype.Bool        `db:"downloaded"`
	ErrorMessage pgtype.Text        `db:"error_message"`
	DownloadedAt pgtype.Timestamptz `db:"downloaded_at"`
	PageID       int32              `db:"page_id"`
}

func (q *Queries) UpdatePageStatus(ctx context.Context, arg UpdatePageStatusParams) error {
	_, err := q.db.Exec(ctx, updatePageStatus,
		arg.Downloaded,
		arg.ErrorMessage,
		arg.DownloadedAt,
		arg.PageID,
	)
	return err
}
